config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# Articles controller definition
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
  end

  def edit; end

  def update
    @article.update(article_params)
  end

  def destroy
    @article.destroy

    redirect_to :root
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <%= form_for(@article) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control ace_editor ace-solarized-light' %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>
<div class="container-buttons">
  <p><%= link_to 'Show', article_path(@article) %> | <%= link_to 'Back', articles_path %></p>
</div>

app/views/articles/index.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <h1><%= link_to article.title, article_path(article) %></h1>
    <p><%= article.content %></p>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>
<div class="container-buttons">
  <p><%= link_to 'Back', articles_path %></p>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="title">
    <h1><%= @article.title %>  <%= link_to '✏️', edit_article_path(@article) %><%= link_to '🗑', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %> </h1>
  </div>
  <p><%= @article.content %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <h2><%= link_to 'Wikiminious', :root %></h2>
      <h2><%= link_to 'New Article', :new_article %></h2>
    </div>
    <%= yield %>
  </body>
</html>